name: ML Run Original
# on mentions a trigger for the workflow
on: 
    push: # when a push is made to the main branch of the repository
      branches:
           - main
jobs:
  ml_run:
    runs-on: ubuntu-latest # runs the workflow on the latest ubuntu version
    container:
      image: jupyter/scipy-notebook:latest # uses the jupyter/scipy-notebook docker image
      options: --user root # runs the container as root user to allow installation of packages
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # uses the checkout action to checkout the code

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scikit-learn
          pip install numpy

      - name: Run the script
        run: |
          python ml_example.py